---
- name: Prepare cluster installation
  hosts: k3s_cluster
  user: ubuntu
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: docker

- name: Create k3s master
  hosts: master
  user: ubuntu
  become: yes
  roles:
    - role: k3s/master

- name: Create k3s nodes
  hosts: node
  user: ubuntu
  become: yes
  roles:
    - role: k3s/node

- name: Rename k3s nodes
  hosts: master
  become: true
  tasks:
    - name: Rename labels in k3s nodes
      command: >-
        kubectl label nodes {{ item }} kubernetes.io/role=worker --overwrite
      loop:
        - node2
        - node3

- name: Install Helm
  hosts: k3s_cluster
  user: ubuntu
  become: yes
  roles:
    - role: helm
  tags: helm
